apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # creationTimestamp: null
  labels:
    io.kompose.service: kafka2-claim1
  name: kafka2-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
